### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by Tsoccerguy3** [MrCrayfish/LegacyVehicles#2]
I'm not sure how finished this is . I saw that you were moving vehicles out of the main mod. I see this does not compile . Is this a placeholder or a add on for the 1.16.5 / 1.17.x / 1.18.x .? Or is this for older minecraft editions?

**Comment by MrCrayfish** [comment]
It won't compile because it's currently using a local maven artifact and this mod is not released yet.

**Comment by MrCrayfish** [comment]
Also you don't need this mod since the currently released version of the vehicle mod still contains these vehicles.

**Comment by Tsoccerguy3** [comment]
Thanks for the info , I was testing the DEV version
